version: "3.10"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn tadreebi.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass

  pgAdmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=tech@tadreebi.com
      - PGADMIN_DEFAULT_PASSWORD=tadreebi
      - SCRIPT_NAME=/pgadmin4
    image: dpage/pgadmin4
    restart: always
    links:
      - database
    ports:
      - 8082:80
