# Generated by Django 4.0.5 on 2022-06-23 16:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='ID number (univesity ID)')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.CharField(choices=[('Amman', 'Amman'), ('Aqaba', 'Aqaba'), ('Irbid', 'Irbid'), ('Jarash', 'Jarash'), ('Mafraq', 'Mafraq'), ('Madaba', 'Madaba'), ('Zarqa', 'Zarqa'), ('Tafilah', 'Tafilah'), ('Salt', 'Salt'), ('Maan', 'Maan'), ('Karak', 'Karak'), ('Ajloun', 'Ajloun')], help_text='city', max_length=32)),
                ('GPA', models.DecimalField(decimal_places=2, help_text='out of 4.00', max_digits=4)),
                ('major', models.CharField(choices=[('IT', 'IT'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Business', 'Business'), ('Medicine', 'Medicine'), ('Law', 'Law'), ('Letreture', 'Letreture')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
