# Generated by Django 4.0.5 on 2022-06-23 17:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=256, null=True)),
                ("intro", models.TextField(blank=True, null=True)),
                ("image", models.CharField(blank=True, max_length=256, null=True)),
                ("job_title", models.CharField(blank=True, max_length=256, null=True)),
                ("experiences", models.JSONField(blank=True, default=[])),
                ("skills", models.JSONField(blank=True, default=[])),
                ("educations", models.JSONField(blank=True, default=[])),
                ("languages", models.JSONField(blank=True, default=[])),
                (
                    "contacts",
                    models.JSONField(
                        blank=True,
                        default={
                            "email": "",
                            "facebook": "",
                            "instagram": "",
                            "linkedin": "",
                            "more": {},
                            "phone_no": "",
                            "telegram": "",
                            "twitter": "",
                            "website": "",
                            "whatsapp": "",
                        },
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.appuser",),
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.appuser",),
        ),
        migrations.CreateModel(
            name="UniversityEmployeeUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
        ),
    ]
