# Generated by Django 4.0.1 on 2022-06-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('job_title', models.CharField(blank=True, max_length=256, null=True)),
                ('experiences', models.JSONField(blank=True, default=[])),
                ('skills', models.JSONField(blank=True, default=[])),
                ('educations', models.JSONField(blank=True, default=[])),
                ('languages', models.JSONField(blank=True, default=[])),
                ('contacts', models.JSONField(blank=True, default={'email': '', 'facebook': '', 'instagram': '', 'linkedin': '', 'more': {}, 'phone_no': '', 'telegram': '', 'twitter': '', 'website': '', 'whatsapp': ''})),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mark', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('training_duration', models.IntegerField(max_length=12)),
                ('report_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
