# Generated by Django 4.0.5 on 2022-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Company account'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='University staff'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
