# Generated by Django 4.0.5 on 2022-06-26 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_studentreport_accepted_studentreport_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('recommend', models.BooleanField(blank=True, null=True)),
                ('detail_experience', models.TextField(blank=True, max_length=256, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
