# Generated by Django 4.0.5 on 2022-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_company_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='out of 4.00, If You are not a student enter 0.00', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='major',
            field=models.CharField(blank=True, choices=[('NOT_A_STUDENT', 'Not a Student'), ('IT', 'IT'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Business', 'Business'), ('Medicine', 'Medicine'), ('Law', 'Law'), ('Letreture', 'Letreture')], default='NOT_A_STUDENT', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(help_text='If you are a (student/university Employee) use the university ID number', max_length=64, unique=True),
        ),
    ]
