# Generated by Django 4.0.5 on 2022-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentreport_accepted_studentreport_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.TextField()),
                ('description', models.TextField()),
                ('schedule', models.TextField()),
                ('location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_of_applications', models.IntegerField(default=0)),
            ],
        ),
    ]
