# Generated by Django 4.0.5 on 2022-06-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unistufeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompUniFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentuser', verbose_name='Student ID (University ID)')),
            ],
        ),
    ]
