# Generated by Django 4.0.1 on 2022-06-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rating_studentreport_accepted_studentreport_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='company_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rating',
            name='recomended',
            field=models.SmallIntegerField(default=5, max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='student_allowed',
            field=models.SmallIntegerField(default=5, max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='support',
            field=models.SmallIntegerField(default=5, max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='useful_train',
            field=models.SmallIntegerField(default=5, max_length=10),
        ),
    ]
