# Generated by Django 4.0.5 on 2022-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compunifeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='compunifeedback',
            name='type',
            field=models.CharField(choices=[('PERIODICAL_REPORT', 'periodical report'), ('COMPLAIN', 'Complain'), ('FEEDBACK', 'Feedback')], default='PERIODICAL_REPORT', max_length=64),
        ),
    ]
