# Generated by Django 4.0.1 on 2022-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rating_company_name_rating_recomended_rating_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.TextField(blank=True, max_length=480, null=True),
        ),
    ]
