# Generated by Django 4.0.4 on 2022-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproposal',
            name='student_Number',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
