# Generated by Django 4.0.5 on 2022-06-26 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_postinternship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postinternship",
            name="num_of_applications",
        ),
        migrations.AddField(
            model_name="postinternship",
            name="company_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="education",
            field=models.CharField(
                choices=[
                    ("Bachelors", "Bachelors"),
                    ("Masters", "Masters"),
                    ("Phd", "Phd"),
                ],
                default="Bachelors",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="experience",
            field=models.CharField(
                choices=[
                    ("No Experience", "No Experience"),
                    ("One Year", "One Year"),
                    ("Two Years", "Two Years"),
                    ("Three Years and Above", "Three Years And Above"),
                ],
                default="No Experience",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Business", "Business"),
                    ("IT", "It"),
                    ("Banking", "Banking"),
                    ("Education", "Education"),
                    ("Engineering", "Engineering"),
                    ("Medical", "Medical"),
                    ("Others", "Others"),
                ],
                default="Business",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="internshipType",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("UnPaid Internship", "Unpaid")],
                default="UnPaid Internship",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="last_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="min_requirements",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="positions",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="salary",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="postinternship",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postinternship",
            name="description",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="postinternship",
            name="location",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="postinternship",
            name="schedule",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Remote", "Remote"),
                ],
                default="Full Time",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="postinternship",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
