# Generated by Django 4.0.4 on 2022-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexperience',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexperience',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
