# Generated by Django 4.0.5 on 2022-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_compunifeedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compunifeedback',
            name='type',
            field=models.CharField(choices=[('PERIODICAL_REPORT', 'periodical report'), ('COMPLAIN', 'Complain')], default='PERIODICAL_REPORT', max_length=64),
        ),
    ]
