# Generated by Django 4.0.5 on 2022-06-27 15:51

import app.models.InternshipPost
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_postinternship_num_of_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinternship',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postinternship',
            name='last_date',
            field=models.DateTimeField(default=app.models.InternshipPost.return_date_time),
        ),
        migrations.AlterField(
            model_name='postinternship',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
