# Generated by Django 4.0.5 on 2022-06-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_postinternship_city_alter_postinternship_last_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postinternship',
            old_name='min_requirements',
            new_name='minimum_requirements',
        ),
    ]
