# Generated by Django 4.0.4 on 2022-06-24 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_student_company_proposal_delete_studentproposal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_company_Proposal',
            new_name='Student_uni_Proposal',
        ),
    ]
