# Generated by Django 4.0.5 on 2022-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_studentapplications_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplications',
            name='university',
            field=models.CharField(choices=[('University of Jordan', 'University Of Jordan'), ('Petra', 'Petra'), ('American University of Madabah', 'American University Of Madabah')], default='University of Jordan', max_length=50),
        ),
    ]
