# Generated by Django 4.0.4 on 2022-06-24 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_rename_student_company_proposal_student_uni_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUniProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('student_Number', models.CharField(max_length=20)),
                ('company_Name', models.CharField(max_length=64)),
                ('company_adress', models.CharField(max_length=256)),
                ('company_phone_number', models.CharField(max_length=15)),
                ('supervisor_Name', models.CharField(max_length=256)),
                ('supervisor_phone_number', models.CharField(max_length=256)),
                ('subervisor_position', models.CharField(max_length=256)),
                ('submission_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_uni_Proposal',
        ),
    ]
