# Generated by Django 4.0.5 on 2022-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='slug',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.SlugField(help_text='If you are a (student/university Employee) use the university ID number', max_length=64, unique=True),
        ),
    ]
