# Generated by Django 4.0.5 on 2022-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentapplications_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplications',
            name='suitable_working_hours',
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='suitable_Internship_Type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Part Time', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='suitable_location',
            field=models.CharField(choices=[('On Site', 'On Site'), ('Remote', 'Remote')], default='On Site', max_length=50),
        ),
    ]
