# Generated by Django 4.0.5 on 2022-06-27 12:22

import app.models.user_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_appuser_slug_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=app.models.user_model.UserNameField(help_text='If you are a (student/university Employee) use the university ID number', max_length=64, unique=True),
        ),
    ]
