# Generated by Django 4.0.5 on 2022-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentuniproposal_delete_student_uni_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuniproposal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentuniproposal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
