# Generated by Django 4.0.5 on 2022-06-27 12:42

import app.models.user_model
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+962*********', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=app.models.user_model.UserNameField(help_text='If you are a (student/university Employee) use the university ID number. If you are a company use the comapany name and replace the spaces with dash (-)', max_length=64, unique=True),
        ),
    ]
