# Generated by Django 4.0.5 on 2022-06-26 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_studentapplications_suitable_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplications',
            name='Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='email',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='gpa',
            field=models.CharField(choices=[('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Excellent', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplications',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
