# Generated by Django 4.0.5 on 2022-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_studentapplications_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplications',
            name='gpa',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Excellent', max_length=50),
        ),
    ]
