# Generated by Django 4.0.5 on 2022-06-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_appuser_phone_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='unistufeedback',
            name='student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.studentuser', verbose_name='Student ID (University ID)'),
        ),
        migrations.AlterField(
            model_name='unistufeedback',
            name='student_username',
            field=models.CharField(default=None, editable=False, max_length=64),
        ),
    ]
