# Generated by Django 4.0.5 on 2022-06-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_unistufeedback_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unistufeedback',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='unistufeedback',
            name='student_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentuser', verbose_name='Student ID (University ID)'),
        ),
    ]
